name: Automatic Minification

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          python3 minify.py
          cp minified-exercises.json /tmp
          git checkout minified
          mv /tmp/minified-exercises.json .
          git add minified-exercises.json
          git commit -m "Minified new exercises.json"
          git push
